### PR TITLE
Updated contributor https://github.com/johnneozucker/

### PR DESCRIPTION
**Pull request by johnneozucker**
Intention is to create a test case
- We would prefer not to overspecialize the prereq images if that is possible.
- Using existing metadataproxy to the max possible.

### CODE REVIEW

**Comment by ryan-lane** [comment]
I just merged another commit. Can you rebase yours to fix the merge conflicts? (we're working on a better process, sorry about this).

**Comment by johnneozucker** [comment]
Hi Ryan - I have rebased and merged into branch neoworks-containerization-roles. Please let me know if there is anything else needed for the process.

**Comment by ryan-lane** [comment]
Hm. There's still merge conflcts. Also, the email address of the commit doesn't match the email address in the contributor file. Can you fix that with your git config and a --reset-author rebase commit?

**Comment by johnneozucker** [comment]
Hi Ryan —

Hopefully my CLA request is approvable?

In the meantime, could I check back with you about the iam:GetRole and sts:AssumeRole settings?

I am assuming that the README you mean is this one . . .
    https://github.com/lyft/metadataproxy/blob/master/README.md  
on the master branch?

In which case it says that the role that I want the container to assume is proxiedaccess-nginx. I have made sure this contains  "sts:AssumeRole”, “iam:GetRole” in its policy. Even so, when I define an IAM_ROLE for a container it still does not locate its STS credentials.

```
# cd /srv/metadataproxy
# source ./config2.sh
[root@ip-172-17-44-212 metadataproxy]# echo . . .
DEFAULT_ROLE is mya-d3-proxiedaccess-nginx, HOST is 0.0.0.0, PORT is 80, MOCK_API is False, METADATA_URL is http://169.254.169.254, ROLE_REVERSE_LOOKUP is False, HOSTNAME_MATCH_REGEX is ^.*$, DOCKER_URL is unix://var/run/docker.sock
# source venv/bin/activate
(venv) [root@ip-172-17-44-212 metadataproxy]# gunicorn wsgi:app --log-level debug --access-logfile /tmp/gunicorn-access --error-logfile /tmp/gunicorn-error --workers=2 -k gevent &
[1] 4619
# docker run -e IAM_ROLE=testcase-proxiedaccess-instance-role --name awstest -it fstab/aws-cli
(env)aws@89d5639df75b:~$ aws sts get-caller-identity  
Unable to locate credentials. You can configure credentials by running "aws configure”.
```

```
                                                              *
```

Overall there is an additional catch. Because I want to launch different containers with different values of IAM_ROLE. So a role mapping file would have been neater. But we can save that problem for another day.

P.S. - I could move this question over to the metadataproxy issues page if preferred. Would I need a branch to call out these questions?

**Comment by ryan-lane** [comment]
Let's discuss metadataproxy issues in that repo. The author infomation looks good now, but there's still merge conflicts with the CONTRIBITORS.md file. Do the following:

``` bash
git fetch
git rebase origin/master
# you'll need to edit CONTRIBUTORS.md to fix the conflicts before this step
git add  CONTRIBITORS.md
git rebase --continue
# now force push to your branch
```

**Comment by dschaller** [comment]
Thanks for your contribution! I am closing this PR as this repository is going to be archived.

**Pull request closed without merging**
