### PR TITLE
Add Max Rozentsveyg to the CLA

### PR DESCRIPTION
**Pull request by mxr**

### CODE REVIEW

**Comment by keith** [comment]
This email address doesn't correspond with the one in your `gitconfig` locally it seems

**Comment by mxr** [comment]
@keith should I change the commit or my git config?

**Comment by keith** [comment]
This is what's in the commit:

```
Author: Max Rozentsveyg <mxr@users.noreply.github.com>
```

It might be because of a github setting to hide your email.

**Comment by mxr** [comment]
I see, changing my config probably won't change that. I would like to keep my email private - can I sign the CLA with the email in the commit?

**Comment by mxr** [comment]
Looks like I do not need to sign the CLA as an employee :)

**Pull request closed without merging**
